[package]
name = "wvr-shadertoy"
version = "0.1.6"
authors = ["gurke.club <contact@gurke.club>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ureq = "2.1"
anyhow = "1.0"
wvr-data = {git = "https://github.com/gurkeclub/wvr-data.git", branch="main"}
